export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const ADD_BOOK_TO_COLLECTION = 'ADD_BOOK_TO_COLLECTION';
export const REMOVE_BOOK_FROM_COLLECTION = 'REMOVE_BOOK_FROM_COLLECTION';
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
